=head1 DESCRIPTION

Flower is a meshed P2P client running between trusted peers on a LAN
or WAN network.

=head1 STATUS

Flower is not yet operational.

=head1 SYNOPSIS

    git clone https://github.com/santex/Flower.git;
    cd Flower;
    dzil build;
    dzil test;
    sudo dzil install;
    pwd=$(pwd);
    ip=127.0.0.1;

    perl $pwd"/bin/flower" --ip $ip --filepath $pwd"/data/"


Then visit L<https://127.0.0.1:2222> in your browser.

=head1 AUTHOR

Hagen Geissler, E<lt>santex@cpan.orgE<gt>

=head1 LICENSE

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
