#!/usr/bin/env perl

use strict;
use warnings;

use Mojo::Base -strict;

use File::Basename 'dirname';
use File::Spec::Functions 'splitdir';

use lib '../lib', 'lib';

use PerlPeer;

use Mojo::Server::Daemon;
use AnyEvent;
use EV;

use Getopt::Long;

use PerlPeer::Files;
use PerlPeer::Nodes;

push @INC, join('/', splitdir(dirname(__FILE__)), '..', 'lib');

# Check if Mojolicious is installed;
die <<EOF unless eval 'use Mojolicious::Commands; 1';  ## no critic
It looks like you don't have the Mojolicious framework installed.
Please visit http://mojolicio.us for detailed installation instructions.

EOF

# Application
$ENV{MOJO_APP} ||= 'PerlPeer';

# Command line options

my $ip;
my $port = 2222;
my $filepath;

my $result = GetOptions ("ip=s"    => \$ip,
			 "port=i"  => \$port,
			 "filepath=s" => \$filepath);

die "need --ip" unless $ip;
die "need --filepath" unless $filepath;
die "$filepath is not a directory" unless -d $filepath;

# Create the Files and Nodes handlers
my $nodes = PerlPeer::Nodes->new($ip, $port);
my $files = PerlPeer::Files->new();
$nodes->self->set_files($files);

# Add our local files
$files->update_all_in_path($filepath);

# Remind us who we are
say "We are " . $nodes->self();

# Add any more nodes
while (my $arg = shift) {
  my ($ip, $port) = split /:/, $arg;
  $nodes->add_if_necessary( { ip => $ip, port => $port } );
}

# Initialise the app and daemon.
my $app = PerlPeer->new();

$app->config->{ nodes } = $nodes;

my $daemon = Mojo::Server::Daemon->new(app => $app, listen => ['https://'.$ip.':'.$port]);
$daemon->start;

# Start EV stuff
my $nodes_timer = AE::timer  1,  5, sub { $nodes->update() };
my $files_timer = AE::timer 10, 10, sub { $files->update_all_in_path($filepath) };

my $cv = AE::cv;
$cv->recv;


__DATA__
#!/usr/bin/env perl

use strict;
use warnings;
use Data::Printer;
use Mojo::Base -strict;
use File::Basename 'dirname';
use File::Spec::Functions qw(rel2abs splitdir);
use PerlPeer;
use PerlPeer::Files;
use PerlPeer::Nodes;
use Mojo::Server::Daemon;
use AnyEvent;
use EV;
use Getopt::Long;

use lib '../lib', 'lib';

push @INC, join('/', splitdir(dirname(__FILE__)), '..', 'lib');

# Check if Mojolicious is installed;
die <<EOF unless eval 'use Mojolicious::Commands; 1';  ## no critic
It looks like you don't have the Mojolicious framework installed.
Please visit http://mojolicio.us for detailed installation instructions.

EOF
BEGIN {
#File::Basename
##IO::Socket::SSL
#
}
# Application
$ENV{MOJO_APP} ||= 'PerlPeer';

# Command line options

my $ip = "172.22.99.165";
my $port = 2222;
my $datapath = rel2abs(dirname(__FILE__));
   $datapath =~ s/script/data/g;
my $filepath = $datapath;
   $filepath =~ s/\/data//g;

   
my $result = GetOptions ("ip=s"    => \$ip,
       "port=i"  => \$port,
       "filepath=s" => \$filepath);

die "need --ip" unless $ip;
die "need --filepath" unless $filepath;
die "$filepath is not a directory" unless -d $filepath;

# Create the Files and Nodes handlers
my $nodes = PerlPeer::Nodes->new($ip, $port);
my $files = PerlPeer::Files->new();
$nodes->self->set_files($files);

# Add our local files
$files->update_all_in_path($filepath);

# Remind us who we are
say "We are " . $nodes->self();

# Add any more nodes
if( !$port ||  !$ip) {
  while (my $arg = shift) {
    my ($ip, $port) = split /:/, $arg;

    $nodes->add_if_necessary( { ip => $ip, port => $port } );
  }

}
# Initialise the app and daemon.
my $app = PerlPeer->new();

$app->config->{ nodes } = $nodes;

my $daemon = Mojo::Server::Daemon->new(app => $app, listen => ['https://'.$ip.':'.$port]);
$daemon->start;

# Start EV stuff
my $micro_timer = AE::timer  1,  5, sub { my $micro = `micro`;  $micro =~s/\n//g;   };
my $nodes_timer = AE::timer  1,  5, sub { $nodes->update() };
my $files_timer = AE::timer 10, 10, sub { $files->update_all_in_path($filepath) };

my $cv = AE::cv;
$cv->recv;
